### PR TITLE
Use codecov instead of coveralls

### PR DESCRIPTION
**Pull request by js636f**

### CODE REVIEW

**Comment by kimberlythegeek** [comment]
#665

**Comment by js636f** [comment]
@kimberlythegeek , I have a question. 
I'm on Windows 10 now and it seems to me it isn't fully suitable for this work. For example it gives this message when installing dependencies (and a lot of warnings):
`info fsevents@1.2.11: The platform "win32" is incompatible with this module.`
When I run tests it gives me a lot of messages like this (but all tests age green):
```
 console.log src/vendor/logs.js:207
      Cannot read property 'map' of undefined
      stacktrace
```
Should I use something like Ubuntu instead of Windows to contribute to this project?
Thanks!

**Comment by kimberlythegeek** [comment]
@js636f You should still be able to run it on Windows. If you have a linux machine already set up, I would suggest using that, but it isn't necessary. 

Did a search for the error message you posted and found this: https://stackoverflow.com/questions/46929196/how-to-solve-npm-install-throwing-fsevents-warning-on-non-mac-os#47071650

Does that help?

**Comment by js636f** [comment]
@kimberlythegeek , Thank you! It seems to me everything works on Windows, but I would like it to work without warnings. I tried `yarn install --ignore-optional`, but the messages are still here (I don't think ignoring warnings is a great idea, but as far as I understand that package isn't necessary in Windows). I'll try something else (npm, I think) and perhaps will finally move to Linux. I'll write if I find something interesting about these issues.

**Comment by kimberlythegeek** [comment]
@js636f sorry to hear you’re having difficulties. It’s not easy for me to help debug because I’m on a different operating system, but I will do my best to help

**Comment by js636f** [comment]
@kimberlythegeek Thank you! I think everything will be fixed soon because these difficulties are not too serious. In fact they are not prevent me from working. They are just a little troubles which can be fixed over time.

**Comment by klahnakoski** [comment]
@js636f  I work on Windows, so I can help if that is still a problem.  Those warnings you mentioned are normal.  Everything still works.  It would be nice to get rid of the warnings, maybe we do not need the `fsevents` library?

The `Cannot read property 'map' of undefined` are warnings, not errors.  They are caused by the fact there is no node network library to make actual network calls during testing.  We should not have real network calls during testing; the intent is to mock those calls, eventually.

**Comment by js636f** [comment]
@klahnakoski , Thank you very much! As I figured out we don't need fsevents on Windows (it's for Mac). I highly appreciate your explanation about those warnings. Now I much more confident in my working setup. Thank you again!

**Comment by js636f** [comment]
@klahnakoski , Thank you! I'm happy to help.

**Pull request merged**
