### PR TITLE
Issue 585 - add desktop cold page tests

### PR DESCRIPTION
**Pull request by airimovici**
https://github.com/mozilla-frontend-infra/firefox-health-dashboard/issues/585

### CODE REVIEW

**Comment by airimovici** [comment]
It looks good on local. There are 3 tests I didn't include for Chrome and Chromium: 
- Instagram binast
- Outlook
- Linkedin

desktop-cold-tests

**Comment by airimovici** [comment]
@klahnakoski Thanks for the review and advice. I included the missing sites, commented out

**Comment by klahnakoski** [comment]
excellent!

**Comment by klahnakoski** [comment]
oops, I merged before dave's review.  We will open an issue if there is a problem

**Comment by davehunt** [comment]
> It looks good on local. There are 3 tests I didn't include for Chrome and Chromium:
>     * Instagram binast
>     * Outlook
>     * Linkedin

Why are we not running outlook and linkedin on Chrome/Chromium?

> oops, I merged before dave's review. We will open an issue if there is a problem

No worries, this looks good to me. We should determine why we're not running those sites against Chrome/Chromium though.

**Comment by airimovici** [comment]
@davehunt I'm investigating this

**Comment by airimovici** [comment]
I created a PR with the fix and the findings after the investigation: https://github.com/mozilla-frontend-infra/firefox-health-dashboard/pull/589

**Pull request merged**
