### PR TITLE
rename to Fluent

### PR DESCRIPTION
**Pull request by klahnakoski**
In an effort to find the right name: How about "fluent"?

https://nikas.praninskas.com/javascript/2015/04/26/fluent-javascript/

### CODE REVIEW

**Comment by klahnakoski** [comment]
this PR requires merges from other branches.  So let us just discuss the name change, not the code.

**Comment by armenzg** [comment]
If it comes to naming, what @sarah-clements recommends seems more clear.

On the topic of method chaining and fluent interfaces, I've found some blog posts that warn us against using this type of programming:
https://www.yegor256.com/2018/03/13/fluent-interfaces.html
https://ocramius.github.io/blog/fluent-interfaces-are-evil/

I can see how it can read a bit better, however, the maintainabilty cost is higher.

**Comment by klahnakoski** [comment]
Fluent Interfaces break Encapsulation
    Fluent Interfaces break Decorators (and sometimes Composition)
    Fluent Interfaces are harder to Mock
    Fluent Interfaces make diffs harder to read
    Fluent Interfaces are less readable (personal feeling)
    Fluent Interfaces cause BC breaks during early development stages

**Comment by klahnakoski** [comment]
Thank you Armen, I did not see your response when I closed this.  To summarize:

[Fluent Interfaces Are Bad for Maintainability](https://www.yegor256.com/2018/03/13/fluent-interfaces.html) biggest point is that the class used to implement the fluent interface can get big, and I can agree the class does get big. I am not convinced a big class is a maintainability problem: The methods in the class will exists as a method somewhere; whether in a single class or scattered throughout the codebase, the program complexity is no worse.  Plus, this page does not consider [extension methods](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/extension-methods);  Allowing the fluent class to remain simple, by delegating the method contracts to other parts of the codebase; no different than declaring a vanilla method. 

[Fluent Interfaces are Evil](https://ocramius.github.io/blog/fluent-interfaces-are-evil/) seems to not apply in this case; either it makes assumptions about the definition of fluent, or assumptions about language restrictiveness, or blames poor programming choices on fluent.  Anyway, this page does serve as a good checklist to avoid pathology.

I will change the name to `chainFrom`

**Pull request closed without merging**
