### PR TITLE
Fix#120 Moved score to CSS grid

### PR DESCRIPTION
**Pull request by sakshi97**
Hi @armenzg . I have changed the score and score-label classes to CSS grid from flex.
Thanks a lot for your suggestions earlier!

### CODE REVIEW

**Comment by armenzg** [comment]
Hi @sakshi97, this is an improvement; congratulations on your first code change landing!
Let me know what kind of issues interest you.

I have manually taken your change into master since I did something naughty which I will not do anymore since it is now more than just me contributing on the repo 😄 I did a `git push -f` on `master` which is not good if more than one person works on a repo as you would have to do a `git pull -f` on `master`. Go ahead and **force** a pull from your `master` branch.

I've also reworded the commit to use a present tense verb and included the issue as `Issue #120`:
https://github.com/mozilla-frontend-infra/firefox-health-dashboard/commit/5e06a32c61bc4b16e9137f39f6d54c09e6f88a20

**Comment by armenzg** [comment]
On another note, after I filed that issue I realized that there's no need to move from flexbox to CSS grids. They both have their own purposes and one is not replacing the other one.
I'm going to close that issue.

**Comment by sakshi97** [comment]
Thanks a lot @armenzg !
I am a beginner (clearly) and want to work on HTML, CSS, Javascript related issues as i find front-end interesting and also have some prior experience. Please do let me know if i can try to tackle any minor issues on that side.

**Comment by armenzg** [comment]
Hi @sakshi97 
This one is a bit harder:
https://github.com/mozilla-frontend-infra/firefox-health-dashboard/issues/115
You could look at the quantum pages and see what changes could be done to improve the view on mobile.

A simpler one would be this one:
https://github.com/mozilla-frontend-infra/firefox-health-dashboard/issues/134

There's also these two projects if you're interested:
https://github.com/mozilla-frontend-infra/js-perf-dashboard
https://github.com/mozilla/firefox-code-coverage-frontend/issues

This current project is a bit more cumbersome as it has a lot of old ways of doing things.
You can help on such end but it will take a lot of back and forth to discuss topics.

Let me know!

**Pull request closed without merging**
