### PR TITLE
Better Bugzilla query logic

### PR DESCRIPTION
**Pull request by klahnakoski**
JSON query expressions are like parsed SQL; they are now used to query Bugzilla, so we have a richer set of logic to filter by

### CODE REVIEW

**Comment by klahnakoski** [comment]
@cpeterso May you look at this PR? If I am updating the queries, I might as well update the chart contents too.

**Comment by klahnakoski** [comment]
The new view

image

**Comment by klahnakoski** [comment]
The important part is the construction of complicated queries using Bugzilla's ?undocumented? Boolean logic.  For example, we convert 

```
{"and":[
	{"eq":{"product":"GeckoView"}},
	{"eq":{"resolution":["---","FIXED"]}},
	{"prefix":{"status_whiteboard.tokenized":"geckoview: fenix: m"}}
]}
```

into 

https://bugzilla.mozilla.org/buglist.cgi?query_format=advanced&f1=OP&j1=AND&f2=product&o2=equals&v2=GeckoView&f3=OP&j3=OR&f4=resolution&o4=equals&v4=---&f5=resolution&o5=equals&v5=FIXED&f6=CP&f7=status_whiteboard&o7=regexp&v7=.*%5C%5Bgeckoview%3Afenix%3Am.*.*&f8=CP&include_fields=priority%2Ccomponent%2Cassigned_to%2Cbug_status%2Cshort_desc%2Cstatus_whiteboard%2Cchangeddate&order=Bug+Number 

which is slightly easier to read with some whitespace:

```
https://bugzilla.mozilla.org/buglist.cgi?
query_format=advanced&
f1=OP&
j1=AND&
    f2=product&
    o2=equals&
    v2=GeckoView&

    f3=OP&
    j3=OR&
        f4=resolution&
        o4=equals&
        v4=---&

        f5=resolution&
        o5=equals&
        v5=FIXED&
    f6=CP&

    f7=status_whiteboard&
    o7=regexp&
    v7=.*%5C%5Bgeckoview%3Afenix%3Am.*.*&
f8=CP&
include_fields=priority%2Ccomponent%2Cassigned_to%2Cbug_status%2Cshort_desc%2Cstatus_whiteboard%2Cchangeddate&
order=Bug+Number
```

**Comment by cpeterso** [comment]
> @cpeterso May you look at this PR? If I am updating the queries, I might as well update the chart contents too.

Good idea. The "Firefox Preview Bugs" chart is out of date because GeckoView's M3, M4, and M5 milestones are completed. 🎉 So that we don't have to update the chart's queries for every new milestone, I suggest the chart show lines for (pseudo-code queries):

* **"GV P1 Bugs":** **(** Product = 'GeckoView' OR Whiteboard contains the substring `[geckoview` **)** AND Priority is one of ['P1', '--'] AND Resolution = '---'
* **"GV P2 Bugs":** **(** Product = 'GeckoView' OR Whiteboard contains the substring `[geckoview` **)** AND Priority = 'P2' AND Resolution = '---'
* **"GV P3 Bugs":** **(** Product = 'GeckoView' OR Whiteboard contains the substring `[geckoview` **)** AND Priority = 'P3' AND Resolution = '---'

Note that the Whiteboard substring `[geckoview` does not include a closing square bracket `]`. This is so the query will match a variety of substrings like `[geckoview]` and `[geckoview:fenix:m6]`.

I think we should include unset Priority '--' (i.e. new bugs not yet triaged) in the P1 query because triaging new bugs is a P1 activity. :) Better that than omitting the untriaged bugs from the chart.

**Comment by klahnakoski** [comment]
@cpeterso please look at this new version; it actually counts the bugs properly.  If you click on the triple dots (...), then you will get all P1 (and triage) in a list.

https://deploy-preview-462--firefox-health-dashboard.netlify.com/android

image

**Comment by cpeterso** [comment]
> @cpeterso please look at this new version; it actually counts the bugs properly. If you click on the triple dots (...), then you will get all P1 (and triage) in a list.
> 
> https://deploy-preview-462--firefox-health-dashboard.netlify.com/android

Looks good! This bird's eye view already shows me that we have too many P1 bugs and should probably lower the priority of some P1 to P2/P3. :)

**Pull request merged**
