### PR TITLE
#333 tests

### PR DESCRIPTION
**Pull request by leslie-alldridge**
#333 basic render tests to improve coverage

- will add more tests to this over time
- package json is identical (checked with diff checker online) but somehow wanted to join the party

### CODE REVIEW

**Comment by leslie-alldridge** [comment]
@klahnakoski hi there, it says build failed as no environment variables are set, however I've only added tests so slightly confused. In my second commit the Android test passes but has an unhandled async request, any tips would be appreciated. Cheers

**Comment by klahnakoski** [comment]
@leslie-alldridge Thank you very much!  

Perform a `yarn lint --fix` to fix the lint errors and push those changes, this will trigger another build/test runs.

I have started to notice a problem in the Travis testing: https://github.com/mozilla-frontend-infra/firefox-health-dashboard/issues/345 . The current solution is to trigger a new build by pushing something.

**Comment by klahnakoski** [comment]
If you push something just to trigger a rerun, please label the commit "trigger build", or something like that so we can see how big a problem it is.  I will do the same over the next week.

**Comment by klahnakoski** [comment]
We may try merging the `errors` branch into this one, and [updating the base branch of this PR](https://stackoverflow.com/questions/10081053/how-to-change-the-base-branch-of-a-pull-request/10081072#10081072)  

The `errors` branch is not merged yet, but should solve a number of the uncaught exceptions

**Comment by klahnakoski** [comment]
Since I like these tests, I will look at this PR next week and ensure they get added to the master branch

**Comment by klahnakoski** [comment]
fixes to merge conflicts here: https://github.com/mozilla-frontend-infra/firefox-health-dashboard/pull/360

**Comment by leslie-alldridge** [comment]
thanks!

**Pull request merged**
