### PR TITLE
add test checklist

### PR DESCRIPTION
**Pull request by klahnakoski**

### CODE REVIEW

**Comment by klahnakoski** [comment]
@aimenbatool @2alin @armenzg 

Anything else I should add to this list?  I will take you comments and add to the PR.

**Comment by armenzg** [comment]
Could you ellaborate what you're looking?
Manual test cases?

**Comment by klahnakoski** [comment]
is the higherIsBetter correct?

**Comment by klahnakoski** [comment]
@armenzg yes, unless we have automated tests, the next best thing is a checklist for manual testing

**Comment by aimenbatool** [comment]
A good read https://github.com/mozilla-frontend-infra/firefox-health-dashboard/issues/211#issuecomment-432418087 

Armen has his feedback as well.

**Comment by armenzg** [comment]
What Aimen points out is good enough.
I think if the Perfherder metadata says higher is better we go ahead and invert the graph and change the Y label from Time(?) to Score.

**Comment by klahnakoski** [comment]
run along the datapoints, back and forth quickly, to see if there are intermittent anomalies

**Comment by 2alin** [comment]
tooltip should position accordingly around the data point?

**Comment by klahnakoski** [comment]
tooltip should show properly even when errorboundary is showing failure component

**Pull request merged**
