### PR TITLE
graph.jsx lazy loading issue

### PR DESCRIPTION
**Pull request by HariShyamU**
Lazy loaded graph.jsx, Added suspense boundaries

### CODE REVIEW

**Comment by klahnakoski** [comment]
@HariShyamU and @the6thm0nth, 

Thank you very much!  This works great, and splits the application into smaller parts.

Before

```
yarn run v1.17.3
$ webpack --mode production
Hash: dd0e835fbaeb16c74be1
Version: webpack 4.40.2
Time: 35132ms
Built at: 11/12/2019 1:05:00 AM
                                       Asset       Size  Chunks                                Chunk Names
                        assets/2.1032e51f.js   1.44 MiB       2  [emitted] [immutable]  [big]
                       assets/2.997bbcd3.css   11.7 KiB       2  [emitted] [immutable]
                    assets/index.24032c5e.js    196 KiB       0  [emitted] [immutable]         index
                   assets/index.8bfe9c52.css   37.8 KiB       0  [emitted] [immutable]         index
```

After

```
yarn run v1.17.3
$ webpack --mode production
Hash: 32d8259f868e882902d4
Version: webpack 4.41.0
Time: 31577ms
Built at: 11/12/2019 1:11:31 AM
                                       Asset       Size  Chunks                                Chunk Names
                        assets/0.43d899e7.js    528 KiB       0  [emitted] [immutable]  [big]
                        assets/4.8b5444a2.js    951 KiB       4  [emitted] [immutable]  [big]
                       assets/4.997bbcd3.css   11.7 KiB       4  [emitted] [immutable]
                        assets/5.47ebe323.js   2.46 KiB       5  [emitted] [immutable]
                    assets/index.1c5bca08.js    200 KiB       1  [emitted] [immutable]         index
                   assets/index.8bfe9c52.css   37.8 KiB       1  [emitted] [immutable]         index
   assets/react-metrics-graphics.fbd8d6e6.js   4.52 KiB       2  [emitted] [immutable]         react-metrics-graphics
```

**Comment by klahnakoski** [comment]
@HariShyamU   One last thing:  Please run `yarn test -u` to update the test templates, commit and push the changes.   Then this is done, and I can merge.  

Thanks again!

**Comment by the6thm0nth** [comment]
@HariShyamU @klahnakoski Super thanks, I couldn't make a time to fix it since I stopped. but thanks to @HariShyamU , this could be merged finally. 👍

**Comment by HariShyamU** [comment]
> @HariShyamU @klahnakoski Super thanks, I couldn't make a time to fix it since I stopped. but thanks to @HariShyamU , this could be merged finally. 👍

No problem. This was my first open source contribution... And it was a lot easier since you fixed most of the issue anyways. Thanks a lot.... I'm slowly getting a gist of this

**Comment by HariShyamU** [comment]
> @HariShyamU One last thing: Please run `yarn test -u` to update the test templates, commit and push the changes. Then this is done, and I can merge.
> 
> Thanks again!

I've done that already. Thanks for this opportunity :)

**Comment by klahnakoski** [comment]
The tests are still not passing. Looking....

**Pull request merged**
