### PR TITLE
Created PR for removing filters for framework

### PR DESCRIPTION
**Pull request by PaliwalArpit**
@klahnakoski Thanks for providing such great details.
I have created an incomplete PR for getting your feedback if I am the right path.

I am a few queries related to filters:

- Inside filters containing suites, we will be adding the same framework and repo for all of them? 
- I am modifying filters inside "BROWSER_PLATFORMS", is that correct?

### CODE REVIEW

**Comment by klahnakoski** [comment]
> Inside filters containing suites, we will be adding the same framework and repo for all of them?

Yes everywhere you see "suite" you should be adding the "framework" and "repo"

> I am modifying filters inside "BROWSER_PLATFORMS", is that correct?

Yes, and just just BROWSER_PLATFORMS, but everywhere else.  Not just this one config file either; there are other config file with this problem.

I notice the work will be redundant; if you have a suggestion of how to add the "framework" and "suite" values programatically, that would be nice too.  Any solution you decide on will be accepted, as long as it works.

**Comment by PaliwalArpit** [comment]
@klahnakoski 
Really appreciated all the details you have provided. This is really exciting to contribute here.
I will try to optimize this to reduce redundancy in filters, so please bear with me so that if I have to go with conventional way to code clean there are lot of places where filters need to be updated.
I am thinking to push multiple commits to keep track of the config that are updated. Please let me know if you have any concerns for time and the way I am doing this.

**Comment by klahnakoski** [comment]
> I am thinking to push multiple commits to keep track of the config that are updated

Good!  Pushing multiple commits is encouraged.  I can see how you are progressing because each commit shows evidence-of-work. It is easier for me to review because I only need to look at the newer commits. Git merge works better with a number of small commits than it does with squashed, or rebased, branches.  Finally, if you happen to disappear, it is easier for me to finish a partial PR than it is start all over again; your name will still be in the commit history.

**Comment by PaliwalArpit** [comment]
@klahnakoski With the last commit, I saw that build was passing, today I am seeing coverage fall with this change, what has been added extra, is there something I can improve?

**Comment by klahnakoski** [comment]
Thank you for getting this PR to pass. 

Do not concern yourself with the decreased coverage:  The tests are unable to use `fetch()`, which means no data, which means less coverage.  We must mock `fetch()` to get coverage:  https://github.com/mozilla-frontend-infra/firefox-health-dashboard/issues/333

**Comment by klahnakoski** [comment]
The code looks fine, so I doubt I will be asking for changes.  You can consider this done.  Since we do not have `fetch()` mocked for testing, I must do manual testing, which I will do later.

Thank you.

**Comment by klahnakoski** [comment]
I have not forgotten about this PR.  I will be merging it, along with others, to be sure there are no inter-PR conflicts.

**Comment by klahnakoski** [comment]
This PR is part of the "Combined PR".  Specifically seen in this changeset

https://github.com/mozilla-frontend-infra/firefox-health-dashboard/pull/649/commits/af701374f5e5c6d6f356469f43204b1081dd7427

Since I had to resolve a conflict, it seems Git/Github could not identify it as a merge, and did not close the PR automatically.

**Pull request closed without merging**
