### PR TITLE
Retired: HOC for errors (version 2)

### PR DESCRIPTION
**Pull request by klahnakoski**

### CODE REVIEW

**Comment by klahnakoski** [comment]
review after merging 

https://github.com/mozilla-frontend-infra/firefox-health-dashboard/pull/329
https://github.com/mozilla-frontend-infra/firefox-health-dashboard/pull/309

**Comment by aimenbatool** [comment]
https://github.com/mozilla-frontend-infra/firefox-health-dashboard/pull/309 is merged!

**Comment by klahnakoski** [comment]
@aimenbatool I am pointing this PR to you so you can see what I have done.  #309 must be merged to make this one appear smaller and easier to digest.

**Comment by armenzg** [comment]
There are some rebase conflicts. Could you please ask for review once it's been dealt with? Thanks

**Comment by klahnakoski** [comment]
@armenzg  you can see the errors starkly on these three pages.

https://deploy-preview-330--firefox-health-dashboard.netlify.com/android
https://deploy-preview-330--firefox-health-dashboard.netlify.com/quantum/64
https://deploy-preview-330--firefox-health-dashboard.netlify.com/quantum/tp6?bits=64&test=loadtime

**Comment by klahnakoski** [comment]
All the previous errors (and stack traces) were intentional: It does show the current brokenness quite starkly.  @armenzg @aimenbatool I made the errors look nicer now.  I merged the https://github.com/mozilla-frontend-infra/firefox-health-dashboard/pull/336 and https://github.com/mozilla-frontend-infra/firefox-health-dashboard/pull/337 into this PR so you can see the fixes those PRs provide.

**Comment by klahnakoski** [comment]
> If so, we have Sentry the complete stacktrace for us to see. We can show a brief message to the user telling them we've reported the issue and they can file an issue at the repo for asking us to investigate.

I know nothing about Sentry, it has not sent me anything.  Also, the Travis builds were throwing errors without stack traces making it difficult to find out where the problem was.   Now they are more verbose too.  These stacktraces now go to the console so I can read them during debugging, even though they are technically handled.

**Pull request closed without merging**
