### PR TITLE
Issue 660 - Add fennec68 results for media playback tests

### PR DESCRIPTION
**Pull request by airimovici**
https://github.com/mozilla-frontend-infra/firefox-health-dashboard/issues/660

### CODE REVIEW

**Comment by airimovici** [comment]
We already have the first results from the fennec68 tests:

https://deploy-preview-661--firefox-health-dashboard.netlify.com/playback/details?platform=g5&browser=fennec68&encoding=VP9&past=2day&ending=2020-02-07

**Comment by davehunt** [comment]
The order looks fine to me. Why are we green on 480p and 720p for Firefox ESR on Pixel 2? It looks like that's not an accurate reflection of the data?

**Comment by airimovici** [comment]
Everything looks fine there from the logs. The number of dropped frames are the same in the logs as they are shown here: https://deploy-preview-661--firefox-health-dashboard.netlify.com/playback/details?platform=p2-aarch64&browser=fennec68&encoding=H264&past=week&ending=2020-02-07. 

Also, the number of decoded frames seem ok: ~460 (u'PlaybackPerf.H264.720p30@2X': {u'droppedFrames': 0, u'decodedFrames': 462})

**Comment by klahnakoski** [comment]
@davehunt I agree with @airimovici   The average number of dropped frames is one, or less on all playback speeds.  more samples may change this

**Comment by davehunt** [comment]
Got it, thanks!

**Pull request merged**
